### ISSUE TITLE
sonnet 3.5 (new) sounds laughable but....

### ISSUE THREAD

**Issue by johndpope** [johndpope/VASA-1-hack#22]
<img width="704" alt="Screenshot 2024-10-30 at 11 50 20 PM" src="https://github.com/user-attachments/assets/f175cc0e-c4e7-4ec1-b127-0e0020f852ec">

https://gist.github.com/johndpope/b3078df813c8b3fc6ac7ede7e97b2ea1

i take another look tomorrow....

fyi @JaLnYn

**Comment by johndpope** [comment]
i cherry pick a bunch of code and merge.

**Comment by JaLnYn** [comment]
I think a big issue with re-implementing vasa is the large amount of VRAM required to train it. A lot of results we get while training does not give good results because contrastive learning requires a huge batch to learn. Unfortunetly I've given up on this project because I don't have the gpu resources to run a big enough batch size.

**Comment by johndpope** [comment]
I asked Microsoft by email today if they were using the 4x a6000 with 24gb or 48gb. It's a show stopper. I rebuilt all of this code over last week (using emoportraits) but loss calculation is throwing OOM with batch size 1 -  but now  I'm relooking at trandformer again.
